// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 10.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Eisk.Tests.IntegrationTests.CodedUiTests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "10.0.30128.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Action_OpenBrowser - Use 'Action_OpenBrowserParams' to pass parameters into this method.
        /// </summary>
        public void Action_OpenBrowser()
        {

            // Go to web page 'about:blank' using new browser instance
            BrowserWindow browser = BrowserWindow.Launch(new System.Uri(this.Action_OpenBrowserParams.Url));
        }
        
        /// <summary>
        /// Action_GoToEmployeeListingPage - Use 'Action_GoToEmployeeListingPageParams' to pass parameters into this method.
        /// </summary>
        public void Action_GoToEmployeeListingPage()
        {
            #region Variable Declarations
            BrowserWindow uIBlankPageWindowsInteWindow = this.UIBlankPageWindowsInteWindow;
            #endregion

            // Go to web page 'http://localhost:3238/Eisk.Web/code-sample/listing-page.aspx'
            uIBlankPageWindowsInteWindow.NavigateToUrl(new System.Uri(this.Action_GoToEmployeeListingPageParams.UIBlankPageWindowsInteWindowUrl));
        }
        
        /// <summary>
        /// Action_ClickAddEmployeeButton
        /// </summary>
        public void Action_ClickAddEmployeeButton()
        {
            #region Variable Declarations
            HtmlInputButton uIAddEmployeeButton = this.UIEmployeeListingPageWWindow.UIEmployeeListingPageDocument.UIAddEmployeeButton;
            #endregion

            // Click 'Add Employee' button
            Mouse.Click(uIAddEmployeeButton, new Point(121, 15));
        }
        
        /// <summary>
        /// Action_RemoveTheRequiredDataFieldsFromEmployeeDetails - Use 'Action_RemoveTheRequiredDataFieldsFromEmployeeDetailsParams' to pass parameters into this method.
        /// </summary>
        public void Action_RemoveTheRequiredDataFieldsFromEmployeeDetails()
        {
            #region Variable Declarations
            HtmlEdit uICtl00ContentPlaceholEdit = this.UIEmployeeDetailsPageWWindow.UIEmployeeDetailsPageDocument.UICtl00ContentPlaceholEdit;
            HtmlEdit uICtl00ContentPlaceholEdit1 = this.UIEmployeeDetailsPageWWindow.UIEmployeeDetailsPageDocument.UICtl00ContentPlaceholEdit1;
            HtmlComboBox uICtl00ContentPlaceholComboBox = this.UIEmployeeDetailsPageWWindow.UIEmployeeDetailsPageDocument.UICtl00ContentPlaceholComboBox;
            HtmlEdit uICtl00ContentPlaceholEdit2 = this.UIEmployeeDetailsPageWWindow.UIEmployeeDetailsPageDocument.UICtl00ContentPlaceholEdit2;
            HtmlEdit uICtl00ContentPlaceholEdit3 = this.UIEmployeeDetailsPageWWindow.UIEmployeeDetailsPageDocument.UICtl00ContentPlaceholEdit3;
            HtmlEdit uICtl00ContentPlaceholEdit4 = this.UIEmployeeDetailsPageWWindow.UIEmployeeDetailsPageDocument.UICtl00ContentPlaceholEdit4;
            HtmlEdit uICtl00ContentPlaceholEdit5 = this.UIEmployeeDetailsPageWWindow.UIEmployeeDetailsPageDocument.UICtl00ContentPlaceholEdit5;
            #endregion

            // Type '' in 'ctl00$ContentPlaceholder1$formViewEmployee$txtFirs...' text box
            uICtl00ContentPlaceholEdit.Text = this.Action_RemoveTheRequiredDataFieldsFromEmployeeDetailsParams.UICtl00ContentPlaceholEditText;

            // Type '' in 'ctl00$ContentPlaceholder1$formViewEmployee$txtLast...' text box
            uICtl00ContentPlaceholEdit1.Text = this.Action_RemoveTheRequiredDataFieldsFromEmployeeDetailsParams.UICtl00ContentPlaceholEdit1Text;

            // Select 'None' in 'ctl00$ContentPlaceholder1$formViewEmployee$ddlCoun...' combo box
            uICtl00ContentPlaceholComboBox.SelectedItem = this.Action_RemoveTheRequiredDataFieldsFromEmployeeDetailsParams.UICtl00ContentPlaceholComboBoxSelectedItem;

            // Type '' in 'ctl00$ContentPlaceholder1$formViewEmployee$txtHire...' text box
            uICtl00ContentPlaceholEdit2.Text = this.Action_RemoveTheRequiredDataFieldsFromEmployeeDetailsParams.UICtl00ContentPlaceholEdit2Text;

            // Type '' in 'ctl00$ContentPlaceholder1$formViewEmployee$txtAddr...' text box
            uICtl00ContentPlaceholEdit3.Text = this.Action_RemoveTheRequiredDataFieldsFromEmployeeDetailsParams.UICtl00ContentPlaceholEdit3Text;

            // Type '' in 'ctl00$ContentPlaceholder1$formViewEmployee$txtHome...' text box
            uICtl00ContentPlaceholEdit4.Text = this.Action_RemoveTheRequiredDataFieldsFromEmployeeDetailsParams.UICtl00ContentPlaceholEdit4Text;

            // Click 'ctl00$ContentPlaceholder1$formViewEmployee$txtExte...' text box
            Mouse.Click(uICtl00ContentPlaceholEdit5, new Point(121, 19));
        }
        
        /// <summary>
        /// Action_ClickSaveMethodOnEmployeeDetails
        /// </summary>
        public void Action_ClickSaveMethodOnEmployeeDetails()
        {
            #region Variable Declarations
            HtmlInputButton uISaveButton = this.UIEmployeeDetailsPageWWindow.UIEmployeeDetailsPageDocument.UISaveButton;
            #endregion

            // Click 'Save' button
            Mouse.Click(uISaveButton, new Point(118, 14));
        }
        
        /// <summary>
        /// Assert_ShouldShowLastNameAsRequiredForEmptyLastNameValue - Use 'Assert_ShouldShowLastNameAsRequiredForEmptyLastNameValueExpectedValues' to pass parameters into this method.
        /// </summary>
        public void Assert_ShouldShowLastNameAsRequiredForEmptyLastNameValue()
        {
            #region Variable Declarations
            HtmlSpan uIRequiredPane = this.UIEmployeeDetailsPageWWindow.UIEmployeeDetailsPageDocument.UIRequiredPane;
            #endregion

            // Verify that 'Required' pane's property 'InnerText' equals 'Required'
            Assert.AreEqual(this.Assert_ShouldShowLastNameAsRequiredForEmptyLastNameValueExpectedValues.UIRequiredPaneInnerText, uIRequiredPane.InnerText);

            // Verify that 'Required' pane's property 'ControlDefinition' equals 'style="VISIBILITY: visible; COLOR: red" id=ctl00_ContentPlaceholder1_formViewEmployee_FieldValidator5  controltovalidate="ctl00_ContentPlaceholder1_formViewEmployee_txtLastName" errormessage="" initialvalue isvalid="false"'
            Assert.AreEqual(this.Assert_ShouldShowLastNameAsRequiredForEmptyLastNameValueExpectedValues.UIRequiredPaneControlDefinition, uIRequiredPane.ControlDefinition);
        }
        
        /// <summary>
        /// Action_CloseBrowserWindow
        /// </summary>
        public void Action_CloseBrowserWindow()
        {
            #region Variable Declarations
            WinButton uICloseButton = this.UIEmployeeDetailsPageWWindow.UIEmployeeDetailsPageWTitleBar.UICloseButton;
            #endregion

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(10, 8));
        }
        
        /// <summary>
        /// Assert_ShouldShowFirstNameAsRequiredForEmptyFirstNameValue - Use 'Assert_ShouldShowFirstNameAsRequiredForEmptyFirstNameValueExpectedValues' to pass parameters into this method.
        /// </summary>
        public void Assert_ShouldShowFirstNameAsRequiredForEmptyFirstNameValue()
        {
            #region Variable Declarations
            HtmlSpan uIRequiredPane1 = this.UIEmployeeDetailsPageWWindow.UIEmployeeDetailsPageDocument.UIRequiredPane1;
            #endregion

            // Verify that 'Required' pane's property 'InnerText' equals 'Required'
            Assert.AreEqual(this.Assert_ShouldShowFirstNameAsRequiredForEmptyFirstNameValueExpectedValues.UIRequiredPane1InnerText, uIRequiredPane1.InnerText);
        }
        
        #region Properties
        public virtual Action_OpenBrowserParams Action_OpenBrowserParams
        {
            get
            {
                if ((this.mAction_OpenBrowserParams == null))
                {
                    this.mAction_OpenBrowserParams = new Action_OpenBrowserParams();
                }
                return this.mAction_OpenBrowserParams;
            }
        }
        
        public virtual Action_GoToEmployeeListingPageParams Action_GoToEmployeeListingPageParams
        {
            get
            {
                if ((this.mAction_GoToEmployeeListingPageParams == null))
                {
                    this.mAction_GoToEmployeeListingPageParams = new Action_GoToEmployeeListingPageParams();
                }
                return this.mAction_GoToEmployeeListingPageParams;
            }
        }
        
        public virtual Action_RemoveTheRequiredDataFieldsFromEmployeeDetailsParams Action_RemoveTheRequiredDataFieldsFromEmployeeDetailsParams
        {
            get
            {
                if ((this.mAction_RemoveTheRequiredDataFieldsFromEmployeeDetailsParams == null))
                {
                    this.mAction_RemoveTheRequiredDataFieldsFromEmployeeDetailsParams = new Action_RemoveTheRequiredDataFieldsFromEmployeeDetailsParams();
                }
                return this.mAction_RemoveTheRequiredDataFieldsFromEmployeeDetailsParams;
            }
        }
        
        public virtual Assert_ShouldShowLastNameAsRequiredForEmptyLastNameValueExpectedValues Assert_ShouldShowLastNameAsRequiredForEmptyLastNameValueExpectedValues
        {
            get
            {
                if ((this.mAssert_ShouldShowLastNameAsRequiredForEmptyLastNameValueExpectedValues == null))
                {
                    this.mAssert_ShouldShowLastNameAsRequiredForEmptyLastNameValueExpectedValues = new Assert_ShouldShowLastNameAsRequiredForEmptyLastNameValueExpectedValues();
                }
                return this.mAssert_ShouldShowLastNameAsRequiredForEmptyLastNameValueExpectedValues;
            }
        }
        
        public virtual Assert_ShouldShowFirstNameAsRequiredForEmptyFirstNameValueExpectedValues Assert_ShouldShowFirstNameAsRequiredForEmptyFirstNameValueExpectedValues
        {
            get
            {
                if ((this.mAssert_ShouldShowFirstNameAsRequiredForEmptyFirstNameValueExpectedValues == null))
                {
                    this.mAssert_ShouldShowFirstNameAsRequiredForEmptyFirstNameValueExpectedValues = new Assert_ShouldShowFirstNameAsRequiredForEmptyFirstNameValueExpectedValues();
                }
                return this.mAssert_ShouldShowFirstNameAsRequiredForEmptyFirstNameValueExpectedValues;
            }
        }
        
        public UIBlankPageWindowsInteWindow UIBlankPageWindowsInteWindow
        {
            get
            {
                if ((this.mUIBlankPageWindowsInteWindow == null))
                {
                    this.mUIBlankPageWindowsInteWindow = new UIBlankPageWindowsInteWindow();
                }
                return this.mUIBlankPageWindowsInteWindow;
            }
        }
        
        public UIEmployeeListingPageWWindow UIEmployeeListingPageWWindow
        {
            get
            {
                if ((this.mUIEmployeeListingPageWWindow == null))
                {
                    this.mUIEmployeeListingPageWWindow = new UIEmployeeListingPageWWindow();
                }
                return this.mUIEmployeeListingPageWWindow;
            }
        }
        
        public UIEmployeeDetailsPageWWindow UIEmployeeDetailsPageWWindow
        {
            get
            {
                if ((this.mUIEmployeeDetailsPageWWindow == null))
                {
                    this.mUIEmployeeDetailsPageWWindow = new UIEmployeeDetailsPageWWindow();
                }
                return this.mUIEmployeeDetailsPageWWindow;
            }
        }
        #endregion
        
        #region Fields
        private Action_OpenBrowserParams mAction_OpenBrowserParams;
        
        private Action_GoToEmployeeListingPageParams mAction_GoToEmployeeListingPageParams;
        
        private Action_RemoveTheRequiredDataFieldsFromEmployeeDetailsParams mAction_RemoveTheRequiredDataFieldsFromEmployeeDetailsParams;
        
        private Assert_ShouldShowLastNameAsRequiredForEmptyLastNameValueExpectedValues mAssert_ShouldShowLastNameAsRequiredForEmptyLastNameValueExpectedValues;
        
        private Assert_ShouldShowFirstNameAsRequiredForEmptyFirstNameValueExpectedValues mAssert_ShouldShowFirstNameAsRequiredForEmptyFirstNameValueExpectedValues;
        
        private UIBlankPageWindowsInteWindow mUIBlankPageWindowsInteWindow;
        
        private UIEmployeeListingPageWWindow mUIEmployeeListingPageWWindow;
        
        private UIEmployeeDetailsPageWWindow mUIEmployeeDetailsPageWWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Action_OpenBrowser'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.30128.1")]
    public class Action_OpenBrowserParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'about:blank' using new browser instance
        /// </summary>
        public string Url = "about:blank";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Action_GoToEmployeeListingPage'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.30128.1")]
    public class Action_GoToEmployeeListingPageParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://localhost:3238/Eisk.Web/code-sample/listing-page.aspx'
        /// </summary>
        public string UIBlankPageWindowsInteWindowUrl = "http://localhost:3238/Eisk.Web/code-sample/listing-page.aspx";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Action_RemoveTheRequiredDataFieldsFromEmployeeDetails'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.30128.1")]
    public class Action_RemoveTheRequiredDataFieldsFromEmployeeDetailsParams
    {
        
        #region Fields
        /// <summary>
        /// Type '' in 'ctl00$ContentPlaceholder1$formViewEmployee$txtFirs...' text box
        /// </summary>
        public string UICtl00ContentPlaceholEditText = "";
        
        /// <summary>
        /// Type '' in 'ctl00$ContentPlaceholder1$formViewEmployee$txtLast...' text box
        /// </summary>
        public string UICtl00ContentPlaceholEdit1Text = "";
        
        /// <summary>
        /// Select 'None' in 'ctl00$ContentPlaceholder1$formViewEmployee$ddlCoun...' combo box
        /// </summary>
        public string UICtl00ContentPlaceholComboBoxSelectedItem = "None";
        
        /// <summary>
        /// Type '' in 'ctl00$ContentPlaceholder1$formViewEmployee$txtHire...' text box
        /// </summary>
        public string UICtl00ContentPlaceholEdit2Text = "";
        
        /// <summary>
        /// Type '' in 'ctl00$ContentPlaceholder1$formViewEmployee$txtAddr...' text box
        /// </summary>
        public string UICtl00ContentPlaceholEdit3Text = "";
        
        /// <summary>
        /// Type '' in 'ctl00$ContentPlaceholder1$formViewEmployee$txtHome...' text box
        /// </summary>
        public string UICtl00ContentPlaceholEdit4Text = "";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Assert_ShouldShowLastNameAsRequiredForEmptyLastNameValue'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.30128.1")]
    public class Assert_ShouldShowLastNameAsRequiredForEmptyLastNameValueExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that 'Required' pane's property 'InnerText' equals 'Required'
        /// </summary>
        public string UIRequiredPaneInnerText = "Required";
        
        /// <summary>
        /// Verify that 'Required' pane's property 'ControlDefinition' equals 'style="VISIBILITY: visible; COLOR: red" id=ctl00_ContentPlaceholder1_formViewEmployee_FieldValidator5  controltovalidate="ctl00_ContentPlaceholder1_formViewEmployee_txtLastName" errormessage="" initialvalue isvalid="false"'
        /// </summary>
        public string UIRequiredPaneControlDefinition = "style=\"VISIBILITY: visible; COLOR: red\" id=ctl00_ContentPlaceholder1_formViewEmpl" +
            "oyee_FieldValidator5  controltovalidate=\"ctl00_ContentPlaceholder1_formViewEmplo" +
            "yee_txtLastName\" errormessage=\"\" initialvalue isvalid=\"false\"";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Assert_ShouldShowFirstNameAsRequiredForEmptyFirstNameValue'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "10.0.30128.1")]
    public class Assert_ShouldShowFirstNameAsRequiredForEmptyFirstNameValueExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that 'Required' pane's property 'InnerText' equals 'Required'
        /// </summary>
        public string UIRequiredPane1InnerText = "Required";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30128.1")]
    public class UIBlankPageWindowsInteWindow : BrowserWindow
    {
        
        public UIBlankPageWindowsInteWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Blank Page";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Blank Page");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30128.1")]
    public class UIEmployeeListingPageWWindow : BrowserWindow
    {
        
        public UIEmployeeListingPageWWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Employee Listing Page";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Employee Listing Page");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIEmployeeListingPageDocument UIEmployeeListingPageDocument
        {
            get
            {
                if ((this.mUIEmployeeListingPageDocument == null))
                {
                    this.mUIEmployeeListingPageDocument = new UIEmployeeListingPageDocument(this);
                }
                return this.mUIEmployeeListingPageDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIEmployeeListingPageDocument mUIEmployeeListingPageDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30128.1")]
    public class UIEmployeeListingPageDocument : HtmlDocument
    {
        
        public UIEmployeeListingPageDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Employee Listing Page";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Eisk.Web/code-sample/listing-page.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:3238/Eisk.Web/code-sample/listing-page.aspx";
            this.WindowTitles.Add("Employee Listing Page");
            #endregion
        }
        
        #region Properties
        public HtmlInputButton UIAddEmployeeButton
        {
            get
            {
                if ((this.mUIAddEmployeeButton == null))
                {
                    this.mUIAddEmployeeButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUIAddEmployeeButton.SearchProperties[HtmlButton.PropertyNames.Id] = "ctl00_ContentPlaceholder1_buttonAdd";
                    this.mUIAddEmployeeButton.SearchProperties[HtmlButton.PropertyNames.Name] = "ctl00$ContentPlaceholder1$buttonAdd";
                    this.mUIAddEmployeeButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = "Add Employee";
                    this.mUIAddEmployeeButton.FilterProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUIAddEmployeeButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIAddEmployeeButton.FilterProperties[HtmlButton.PropertyNames.Class] = "button-search";
                    this.mUIAddEmployeeButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "accessKey=a style=\"WIDTH: 150px\" id=ctl0";
                    this.mUIAddEmployeeButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "49";
                    this.mUIAddEmployeeButton.WindowTitles.Add("Employee Listing Page");
                    #endregion
                }
                return this.mUIAddEmployeeButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlInputButton mUIAddEmployeeButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30128.1")]
    public class UIEmployeeDetailsPageWWindow : BrowserWindow
    {
        
        public UIEmployeeDetailsPageWWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Employee Details Page";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Employee Details Page");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIEmployeeDetailsPageDocument UIEmployeeDetailsPageDocument
        {
            get
            {
                if ((this.mUIEmployeeDetailsPageDocument == null))
                {
                    this.mUIEmployeeDetailsPageDocument = new UIEmployeeDetailsPageDocument(this);
                }
                return this.mUIEmployeeDetailsPageDocument;
            }
        }
        
        public UIEmployeeDetailsPageWTitleBar UIEmployeeDetailsPageWTitleBar
        {
            get
            {
                if ((this.mUIEmployeeDetailsPageWTitleBar == null))
                {
                    this.mUIEmployeeDetailsPageWTitleBar = new UIEmployeeDetailsPageWTitleBar(this);
                }
                return this.mUIEmployeeDetailsPageWTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIEmployeeDetailsPageDocument mUIEmployeeDetailsPageDocument;
        
        private UIEmployeeDetailsPageWTitleBar mUIEmployeeDetailsPageWTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30128.1")]
    public class UIEmployeeDetailsPageDocument : HtmlDocument
    {
        
        public UIEmployeeDetailsPageDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Employee Details Page";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Eisk.Web/code-sample/details-page.aspx";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:3238/Eisk.Web/code-sample/details-page.aspx";
            this.WindowTitles.Add("Employee Details Page");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UICtl00ContentPlaceholEdit
        {
            get
            {
                if ((this.mUICtl00ContentPlaceholEdit == null))
                {
                    this.mUICtl00ContentPlaceholEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUICtl00ContentPlaceholEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "ctl00_ContentPlaceholder1_formViewEmployee_txtFirstName";
                    this.mUICtl00ContentPlaceholEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "ctl00$ContentPlaceholder1$formViewEmployee$txtFirstName";
                    this.mUICtl00ContentPlaceholEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUICtl00ContentPlaceholEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUICtl00ContentPlaceholEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUICtl00ContentPlaceholEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUICtl00ContentPlaceholEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "id=ctl00_ContentPlaceholder1_formViewEmp";
                    this.mUICtl00ContentPlaceholEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "7";
                    this.mUICtl00ContentPlaceholEdit.WindowTitles.Add("Employee Details Page");
                    #endregion
                }
                return this.mUICtl00ContentPlaceholEdit;
            }
        }
        
        public HtmlEdit UICtl00ContentPlaceholEdit1
        {
            get
            {
                if ((this.mUICtl00ContentPlaceholEdit1 == null))
                {
                    this.mUICtl00ContentPlaceholEdit1 = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUICtl00ContentPlaceholEdit1.SearchProperties[HtmlEdit.PropertyNames.Id] = "ctl00_ContentPlaceholder1_formViewEmployee_txtLastName";
                    this.mUICtl00ContentPlaceholEdit1.SearchProperties[HtmlEdit.PropertyNames.Name] = "ctl00$ContentPlaceholder1$formViewEmployee$txtLastName";
                    this.mUICtl00ContentPlaceholEdit1.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUICtl00ContentPlaceholEdit1.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUICtl00ContentPlaceholEdit1.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUICtl00ContentPlaceholEdit1.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUICtl00ContentPlaceholEdit1.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "id=ctl00_ContentPlaceholder1_formViewEmp";
                    this.mUICtl00ContentPlaceholEdit1.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "8";
                    this.mUICtl00ContentPlaceholEdit1.WindowTitles.Add("Employee Details Page");
                    #endregion
                }
                return this.mUICtl00ContentPlaceholEdit1;
            }
        }
        
        public HtmlComboBox UICtl00ContentPlaceholComboBox
        {
            get
            {
                if ((this.mUICtl00ContentPlaceholComboBox == null))
                {
                    this.mUICtl00ContentPlaceholComboBox = new HtmlComboBox(this);
                    #region Search Criteria
                    this.mUICtl00ContentPlaceholComboBox.SearchProperties[HtmlComboBox.PropertyNames.Id] = "ctl00_ContentPlaceholder1_formViewEmployee_ddlCountry";
                    this.mUICtl00ContentPlaceholComboBox.SearchProperties[HtmlComboBox.PropertyNames.Name] = "ctl00$ContentPlaceholder1$formViewEmployee$ddlCountry";
                    this.mUICtl00ContentPlaceholComboBox.FilterProperties[HtmlComboBox.PropertyNames.Size] = "0";
                    this.mUICtl00ContentPlaceholComboBox.FilterProperties[HtmlComboBox.PropertyNames.LabeledBy] = null;
                    this.mUICtl00ContentPlaceholComboBox.FilterProperties[HtmlComboBox.PropertyNames.Title] = null;
                    this.mUICtl00ContentPlaceholComboBox.FilterProperties[HtmlComboBox.PropertyNames.ItemCount] = "3";
                    this.mUICtl00ContentPlaceholComboBox.FilterProperties[HtmlComboBox.PropertyNames.Class] = null;
                    this.mUICtl00ContentPlaceholComboBox.FilterProperties[HtmlComboBox.PropertyNames.ControlDefinition] = "id=ctl00_ContentPlaceholder1_formViewEmp";
                    this.mUICtl00ContentPlaceholComboBox.FilterProperties[HtmlComboBox.PropertyNames.TagInstance] = "1";
                    this.mUICtl00ContentPlaceholComboBox.WindowTitles.Add("Employee Details Page");
                    #endregion
                }
                return this.mUICtl00ContentPlaceholComboBox;
            }
        }
        
        public HtmlEdit UICtl00ContentPlaceholEdit2
        {
            get
            {
                if ((this.mUICtl00ContentPlaceholEdit2 == null))
                {
                    this.mUICtl00ContentPlaceholEdit2 = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUICtl00ContentPlaceholEdit2.SearchProperties[HtmlEdit.PropertyNames.Id] = "ctl00_ContentPlaceholder1_formViewEmployee_txtHireDate";
                    this.mUICtl00ContentPlaceholEdit2.SearchProperties[HtmlEdit.PropertyNames.Name] = "ctl00$ContentPlaceholder1$formViewEmployee$txtHireDate";
                    this.mUICtl00ContentPlaceholEdit2.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUICtl00ContentPlaceholEdit2.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUICtl00ContentPlaceholEdit2.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUICtl00ContentPlaceholEdit2.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUICtl00ContentPlaceholEdit2.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "id=ctl00_ContentPlaceholder1_formViewEmp";
                    this.mUICtl00ContentPlaceholEdit2.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "12";
                    this.mUICtl00ContentPlaceholEdit2.WindowTitles.Add("Employee Details Page");
                    #endregion
                }
                return this.mUICtl00ContentPlaceholEdit2;
            }
        }
        
        public HtmlEdit UICtl00ContentPlaceholEdit3
        {
            get
            {
                if ((this.mUICtl00ContentPlaceholEdit3 == null))
                {
                    this.mUICtl00ContentPlaceholEdit3 = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUICtl00ContentPlaceholEdit3.SearchProperties[HtmlEdit.PropertyNames.Id] = "ctl00_ContentPlaceholder1_formViewEmployee_txtAddress";
                    this.mUICtl00ContentPlaceholEdit3.SearchProperties[HtmlEdit.PropertyNames.Name] = "ctl00$ContentPlaceholder1$formViewEmployee$txtAddress";
                    this.mUICtl00ContentPlaceholEdit3.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUICtl00ContentPlaceholEdit3.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUICtl00ContentPlaceholEdit3.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUICtl00ContentPlaceholEdit3.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUICtl00ContentPlaceholEdit3.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "id=ctl00_ContentPlaceholder1_formViewEmp";
                    this.mUICtl00ContentPlaceholEdit3.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "13";
                    this.mUICtl00ContentPlaceholEdit3.WindowTitles.Add("Employee Details Page");
                    #endregion
                }
                return this.mUICtl00ContentPlaceholEdit3;
            }
        }
        
        public HtmlEdit UICtl00ContentPlaceholEdit4
        {
            get
            {
                if ((this.mUICtl00ContentPlaceholEdit4 == null))
                {
                    this.mUICtl00ContentPlaceholEdit4 = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUICtl00ContentPlaceholEdit4.SearchProperties[HtmlEdit.PropertyNames.Id] = "ctl00_ContentPlaceholder1_formViewEmployee_txtHomePhone";
                    this.mUICtl00ContentPlaceholEdit4.SearchProperties[HtmlEdit.PropertyNames.Name] = "ctl00$ContentPlaceholder1$formViewEmployee$txtHomePhone";
                    this.mUICtl00ContentPlaceholEdit4.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUICtl00ContentPlaceholEdit4.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUICtl00ContentPlaceholEdit4.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUICtl00ContentPlaceholEdit4.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUICtl00ContentPlaceholEdit4.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "id=ctl00_ContentPlaceholder1_formViewEmp";
                    this.mUICtl00ContentPlaceholEdit4.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "17";
                    this.mUICtl00ContentPlaceholEdit4.WindowTitles.Add("Employee Details Page");
                    #endregion
                }
                return this.mUICtl00ContentPlaceholEdit4;
            }
        }
        
        public HtmlEdit UICtl00ContentPlaceholEdit5
        {
            get
            {
                if ((this.mUICtl00ContentPlaceholEdit5 == null))
                {
                    this.mUICtl00ContentPlaceholEdit5 = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUICtl00ContentPlaceholEdit5.SearchProperties[HtmlEdit.PropertyNames.Id] = "ctl00_ContentPlaceholder1_formViewEmployee_txtExtension";
                    this.mUICtl00ContentPlaceholEdit5.SearchProperties[HtmlEdit.PropertyNames.Name] = "ctl00$ContentPlaceholder1$formViewEmployee$txtExtension";
                    this.mUICtl00ContentPlaceholEdit5.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUICtl00ContentPlaceholEdit5.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUICtl00ContentPlaceholEdit5.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUICtl00ContentPlaceholEdit5.FilterProperties[HtmlEdit.PropertyNames.Class] = null;
                    this.mUICtl00ContentPlaceholEdit5.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "id=ctl00_ContentPlaceholder1_formViewEmp";
                    this.mUICtl00ContentPlaceholEdit5.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "18";
                    this.mUICtl00ContentPlaceholEdit5.WindowTitles.Add("Employee Details Page");
                    #endregion
                }
                return this.mUICtl00ContentPlaceholEdit5;
            }
        }
        
        public HtmlInputButton UISaveButton
        {
            get
            {
                if ((this.mUISaveButton == null))
                {
                    this.mUISaveButton = new HtmlInputButton(this);
                    #region Search Criteria
                    this.mUISaveButton.SearchProperties[HtmlButton.PropertyNames.Id] = "ctl00_ContentPlaceholder1_formViewEmployee_btnSave";
                    this.mUISaveButton.SearchProperties[HtmlButton.PropertyNames.Name] = "ctl00$ContentPlaceholder1$formViewEmployee$btnSave";
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.DisplayText] = "Save";
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.Type] = "submit";
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.Class] = "button-search";
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "accessKey=s style=\"WIDTH: 150px\" id=ctl0";
                    this.mUISaveButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "21";
                    this.mUISaveButton.WindowTitles.Add("Employee Details Page");
                    #endregion
                }
                return this.mUISaveButton;
            }
        }
        
        public HtmlSpan UIRequiredPane
        {
            get
            {
                if ((this.mUIRequiredPane == null))
                {
                    this.mUIRequiredPane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUIRequiredPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "ctl00_ContentPlaceholder1_formViewEmployee_RequiredFieldValidator5";
                    this.mUIRequiredPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIRequiredPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Required";
                    this.mUIRequiredPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIRequiredPane.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIRequiredPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "style=\"VISIBILITY: visible; COLOR: red\" ";
                    this.mUIRequiredPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "7";
                    this.mUIRequiredPane.WindowTitles.Add("Employee Details Page");
                    #endregion
                }
                return this.mUIRequiredPane;
            }
        }
        
        public HtmlSpan UIRequiredPane1
        {
            get
            {
                if ((this.mUIRequiredPane1 == null))
                {
                    this.mUIRequiredPane1 = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUIRequiredPane1.SearchProperties[HtmlDiv.PropertyNames.Id] = "ctl00_ContentPlaceholder1_formViewEmployee_rfvFirstName";
                    this.mUIRequiredPane1.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIRequiredPane1.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Required";
                    this.mUIRequiredPane1.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIRequiredPane1.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
                    this.mUIRequiredPane1.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "style=\"VISIBILITY: visible; COLOR: red\" ";
                    this.mUIRequiredPane1.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "5";
                    this.mUIRequiredPane1.WindowTitles.Add("Employee Details Page");
                    #endregion
                }
                return this.mUIRequiredPane1;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUICtl00ContentPlaceholEdit;
        
        private HtmlEdit mUICtl00ContentPlaceholEdit1;
        
        private HtmlComboBox mUICtl00ContentPlaceholComboBox;
        
        private HtmlEdit mUICtl00ContentPlaceholEdit2;
        
        private HtmlEdit mUICtl00ContentPlaceholEdit3;
        
        private HtmlEdit mUICtl00ContentPlaceholEdit4;
        
        private HtmlEdit mUICtl00ContentPlaceholEdit5;
        
        private HtmlInputButton mUISaveButton;
        
        private HtmlSpan mUIRequiredPane;
        
        private HtmlSpan mUIRequiredPane1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "10.0.30128.1")]
    public class UIEmployeeDetailsPageWTitleBar : WinTitleBar
    {
        
        public UIEmployeeDetailsPageWTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Employee Details Page");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Employee Details Page");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
}
